GoodSpace-Kr/Backend

- build.gradle
- src/main/java/goodspace/backend/security/JwtFilter.java
- src/main/java/goodspace/backend/security/RefreshToken.java
- src/main/java/goodspace/backend/security/SecurityConfig.java
- src/main/java/goodspace/backend/security/TokenProvider.java
- src/main/java/goodspace/backend/security/TokenType.java
JWT 기반 Spring Security 설정 파일을 생성했습니다.
#3 
회원가입/로그인 로직을 구현하며 설정 파일에 이상한 점이 없는지 확인하겠습니다.
> [feat/#3] Spring Security 설정 등록

- src/main/java/goodspace/backend/controller/UserController.java
- src/main/java/goodspace/backend/domain/Order.java
- src/main/java/goodspace/backend/domain/user/Delivery.java
- src/main/java/goodspace/backend/domain/user/User.java
- src/main/java/goodspace/backend/dto/UserMyPageDto.java
- src/main/java/goodspace/backend/repository/UserRepository.java
- src/main/java/goodspace/backend/service/UserService.java
UserController 생성
UserMyPageDto 생성
UserRepository 생성
UserService 생성
후 
Mypage업데이트 하는 API작성하였습니다.
`public User setUserFromUserMyPageDto(UserMyPageDto userMyPageDto)`
함수와 
`public static Delivery from(UserMyPageDto userMyPageDto)`
함수 테스트 코드 작성 완료
> [feat/#17] update MyPage API complete

- Dockerfile
- docker-compose.yml
배포를 위한 Docker 관련 파일들을 생성했습니다.
#34
> [feat/#34] Docker 관련 파일 생성

- src/main/java/goodspace/backend/admin/service/AdminInitializeService.java
- src/main/java/goodspace/backend/authorization/dto/request/SignUpRequestDto.java
- src/main/java/goodspace/backend/authorization/service/goodspace/GoodSpaceAuthorizationServiceImpl.java
- src/main/java/goodspace/backend/global/password/PasswordValidator.java
- src/main/java/goodspace/backend/global/password/PasswordValidatorImpl.java
- src/main/java/goodspace/backend/global/security/SecurityConfig.java
- src/main/java/goodspace/backend/user/controller/UserController.java
- src/main/java/goodspace/backend/user/dto/PasswordUpdateRequestDto.java
- src/main/java/goodspace/backend/user/dto/RefreshTokenResponseDto.java
- src/main/java/goodspace/backend/user/repository/UserRepository.java
- src/main/java/goodspace/backend/user/service/UserService.java
- src/test/java/goodspace/backend/authorization/password/PasswordValidatorTest.java
- src/test/java/goodspace/backend/authorization/service/goodspace/GoodSpaceAuthorizationServiceTest.java
- src/test/java/goodspace/backend/user/service/UserServiceTest.java
비밀번호 해싱을 통해 DB 유출시 회원의 비밀번호가 유출되지 않게 개선했습니다.
#67
> [feat/#67] 비밀번호 해싱 구현

- src/main/java/goodspace/backend/admin/controller/AdminQuestionController.java
> update name of registerAnswer method

- src/main/java/goodspace/backend/qna/controller/QuestionController.java
- src/main/java/goodspace/backend/qna/dto/AllQuestionResponseDto.java
- src/main/java/goodspace/backend/qna/repository/QuestionRepository.java
- src/main/java/goodspace/backend/qna/service/QuestionService.java
> [feat/#94] getAllQuestions API creation

- src/main/java/goodspace/backend/qna/controller/QuestionController.java
- src/main/java/goodspace/backend/qna/service/QuestionService.java
> [feat/#96] modify parameter id -> principle in getUserQuestions

- src/main/java/goodspace/backend/qna/controller/QuestionController.java
- src/main/java/goodspace/backend/qna/domain/Question.java
- src/main/java/goodspace/backend/qna/service/QuestionService.java
> [feature] modifyQuestion creation

- src/main/java/goodspace/backend/qna/dto/AnswerDto.java
- src/main/java/goodspace/backend/qna/dto/QuestionResponseDto.java
- src/main/java/goodspace/backend/qna/service/QuestionService.java
> [feat/#107] create AnswerDto and insert in getQuestion API

- src/main/java/goodspace/backend/qna/controller/QuestionController.java
- src/main/java/goodspace/backend/qna/dto/QuestionFileDto.java
- src/main/java/goodspace/backend/qna/dto/QuestionResponseDto.java
- src/main/java/goodspace/backend/qna/service/QuestionService.java
> delete getFile and modify getQuestion to have files

- src/main/java/goodspace/backend/qna/dto/QuestionResponseDto.java
- src/main/java/goodspace/backend/qna/service/QuestionService.java
> add createAt field in getQuestion

- src/main/java/goodspace/backend/order/controller/OrderController.java
- src/main/java/goodspace/backend/order/domain/Order.java
- src/main/java/goodspace/backend/order/service/OrderService.java
- src/main/java/goodspace/backend/qna/controller/QuestionController.java
- src/main/java/goodspace/backend/qna/service/QuestionService.java
> [feat/#118] modify modifyQuestion API with files

- src/main/resources/templates/nicepay.html
> nicepay redirect url modify

- src/main/java/goodspace/backend/cart/domain/CartItem.java
- src/main/java/goodspace/backend/cart/dto/CartItemInfoResponseDto.java
- src/main/java/goodspace/backend/cart/service/CartItemServiceImpl.java
- src/main/java/goodspace/backend/client/domain/Client.java
- src/main/java/goodspace/backend/email/entity/EmailVerification.java
- src/main/java/goodspace/backend/global/domain/Item.java
- src/main/java/goodspace/backend/global/repository/CartItemRepository.java
- src/main/java/goodspace/backend/order/domain/Order.java
- src/main/java/goodspace/backend/order/domain/OrderCartItem.java
- src/main/java/goodspace/backend/qna/domain/Answer.java
- src/main/java/goodspace/backend/qna/domain/Question.java
- src/main/java/goodspace/backend/qna/domain/QuestionFile.java
- src/main/java/goodspace/backend/user/domain/GoodSpaceUser.java
- src/main/java/goodspace/backend/user/domain/OAuthUser.java
- src/main/java/goodspace/backend/user/domain/User.java
- src/main/java/goodspace/backend/user/domain/UserRole.java
- src/test/java/goodspace/backend/admin/service/item/ItemManageServiceTest.java
- src/test/java/goodspace/backend/admin/service/itemImage/ItemImageManageServiceTest.java
- src/test/java/goodspace/backend/admin/service/question/AdminQuestionServiceTest.java
- src/test/java/goodspace/backend/cart/service/CartItemServiceTest.java
- src/test/java/goodspace/backend/client/service/ClientServiceTest.java
- src/test/java/goodspace/backend/fixture/ItemFixture.java
- src/test/java/goodspace/backend/fixture/QuestionFixture.java
데이터베이스 제약조건을 강화했습니다.
제약조건 변경에 맞게 테스트 코드를 수정했습니다.
#113
> [chore/#113] 데이터베이스 제약조건 강화

- src/main/java/goodspace/backend/qna/controller/QuestionController.java
> [feat/#139] add QnA summary and description to Swagger

- src/main/java/goodspace/backend/order/controller/NicePayController.java
- src/main/java/goodspace/backend/order/domain/Order.java
- src/main/java/goodspace/backend/order/domain/OrderStatus.java
- src/main/java/goodspace/backend/order/domain/PaymentApproveResult.java
- src/main/java/goodspace/backend/order/dto/OrderResponseDto.java
- src/main/java/goodspace/backend/order/repository/OrderRepository.java
- src/main/java/goodspace/backend/order/service/NicePayService.java
- src/main/java/goodspace/backend/order/service/OrderService.java
> [임시커밋] for orderId and orderStatus

- src/main/java/goodspace/backend/order/dto/OrderRequestDto.java
> 임시커밋 delete orderId in OrderRequestDto

- src/main/java/goodspace/backend/order/controller/OrderController.java
- src/main/java/goodspace/backend/order/service/OrderService.java
> 임시커밋 create deleteOrder

- src/main/java/goodspace/backend/order/controller/OrderController.java
- src/main/java/goodspace/backend/order/dto/OrderCreateResponseDto.java
> modify createOrder Response

- src/main/java/goodspace/backend/authorization/controller/OAuthController.java
- src/main/java/goodspace/backend/authorization/dto/naver/NaverAppAuthRequestDto.java
네이버 SDK의 캐싱 문제로 인해, 통신 방식을 POST + RequestBody로 변경했습니다.
> [refactor] 네이버 앱 Auth의 통신 방식 수정

- src/main/java/goodspace/backend/global/exception/GlobalExceptionHandler.java
> [chore/#161] HTTP 예외 핸들링

- src/main/java/goodspace/backend/order/controller/NicePayController.java
> [feat/#171] modify app scheme

- src/main/java/goodspace/backend/cart/dto/CartItemInfoResponseDto.java
- src/test/java/goodspace/backend/cart/service/CartItemServiceTest.java
장바구니 상품 조회 API가 상품의 ID도 반환하도록 수정했습니다.
> [fix] 장바구니 API 응답값 수정

- src/main/java/goodspace/backend/order/dto/OrderInfoDto.java
- src/main/java/goodspace/backend/order/dto/OrderRequestDto.java
- src/main/java/goodspace/backend/order/service/OrderService.java
- src/main/java/goodspace/backend/user/domain/User.java
주문 시점에 회원 정보를 업데이트할 수 있도록 로직을 추가했습니다.
#207
> [chore/#207] 주문시 회원 정보를 저장하는 로직 추가

- src/main/java/goodspace/backend/global/exception/GlobalExceptionHandler.java
`GlobalExceptionHandler`가 더 다양한 예외를 핸들링하도록 개선했습니다.
> [chore] GlobalExceptionHandler 개선

- src/main/java/goodspace/backend/qna/service/QuestionService.java
답변 완료된 문의는 수정할 수 없도록 검증 로직을 추가했습니다.
#231
> [chore/#231] 답변 대기중인 문의만 수정할 수 있도록 검증 로직 추가

- src/main/java/goodspace/backend/order/controller/OrderController.java
- src/main/java/goodspace/backend/qna/controller/QuestionController.java
- src/main/java/goodspace/backend/shipping/controller/ShippingTraceController.java
> [feat/#170] API URL modify by restful API
